### ISSUE TITLE
Rename all MBed to Mbed

### ISSUE THREAD

**Issue by ladislas** [USCRPL/mbed-cmake#11]
This might be my OCD speaking: In a lot of places in code, documentation and wiki, `Mbed` is referred as `MBed` but the official spelling is `Mbed`.

I'd feel better if we could have the right spelling everywhere :)

I can also work on a PR (not in the wiki though, I don't know how to do that).

**Comment by multiplemonomials** [comment]
Aw jeez I hadn't noticed this until now... I guess I'll start fixing it where I see it.
