### ISSUE TITLE
Pass custom profile.json

### ISSUE THREAD

**Issue by ladislas** [USCRPL/mbed-cmake#16]
When using mbed-cli, I pass a custom profile with additional options like this:

```
mbed compile -m DISCO_ORIGINAL --profile=release --profile=./profiles/leka.json
```

How can I do the same with mbed-cmake? (it must be super simple but I can seem to find it...)

**Comment by multiplemonomials** [comment]
Currently this doesn't exist sadly.  It would require some modifications to configure_for_target.py.  I am wondering, is there anything that you can do with a profile.json that you can't also do by adding flags in CMake?

**Comment by ladislas** [comment]
> I am wondering, is there anything that you can do with a profile.json that you can't also do by adding flags in CMake?

No, that's what I figured and what I'll do! Thanks for the answer :)
