### ISSUE TITLE
Supply custom `.mbedignore`

### ISSUE THREAD

**Issue by ProExpertProg** [USCRPL/mbed-cmake#39]
Currently, one has to modify the `.mbedignore` inside `mbed-src`. Could we add an option to supply a custom `.mbedignore` file when running `configure_for_target.py`? Would help anyone using this as a submodule.

**Comment by multiplemonomials** [comment]
This already exists!  It's the `-i` option to configure_for_target.py.

**Comment by ProExpertProg** [comment]
Was it added in 1.8? I haven't upgraded back after that failure

**Comment by ProExpertProg** [comment]
Yup I see it now. Tested & it works as expected.
