### ISSUE TITLE
mingw32-make got Error1 && Error2

### ISSUE THREAD

**Issue by nasihs** [USCRPL/mbed-cmake#40]
I followed the steps in Getting Started.
Everything worked smoothly until I tried **mingw32-make -j2 hello_world**.
The outputs are as follows
It would be very nice of you if you could help.
![cmake_error](https://user-images.githubusercontent.com/41518918/142173954-882ba1d1-63c7-4182-bb71-4c4aecdfb1a2.png)
![cmake_error2](https://user-images.githubusercontent.com/41518918/142173970-6b52ab45-e23f-4dc2-a7c8-939c7fc0aa78.png)

**Comment by multiplemonomials** [comment]
Hmm, this might be due to command line length limits on Windows, I've seen issues with that before.  Try installing [ninja-build](https://ninja-build.org/) (just drop the exe somewhere on your path), delete your build dir, then rerun cmake with `-GNinja` instead of `-GMinGW Makefiles`.

**Comment by nasihs** [comment]
> Hmm, this might be due to command line length limits on Windows, I've seen issues with that before. Try installing [ninja-build](https://ninja-build.org/) (just drop the exe somewhere on your path), delete your build dir, then rerun cmake with `-GNinja` instead of `-GMinGW Makefiles`.

Thanks for your attention.
I installed ninja and ran cmake -GNinja, ninja in the build directory, I got a ninja fatal error: Is the command too long?
![long](https://user-images.githubusercontent.com/41518918/142602420-a731cfbc-43c0-4b13-8d6c-977429c167f1.png)

![ninja1](https://user-images.githubusercontent.com/41518918/142598145-b7a5ae8e-6186-44ef-bd92-7bc33fc26546.png)

![ninja222](https://user-images.githubusercontent.com/41518918/142598241-b6539df9-c733-4aab-8402-4e49ff4e3822.png)

Then I searched for the resolution and got this: https://stackoverflow.com/questions/43184251/cmake-command-line-too-long-windows
![answer](https://user-images.githubusercontent.com/41518918/142596457-d1f451ad-a00f-4e5e-a4c5-44fe4ad5aaa5.png)

As I'm new to cmake, I don't know what the toolchain file specifies and I just added the settings in the root CMakeLists.txt like this:

![cmakelists](https://user-images.githubusercontent.com/41518918/142597719-46ecca34-e083-4486-9908-74a52dafeefd.png)

I got a fatal error when I reran ninja. I checked the directory and found that as.exe did exist.

![ninja333333](https://user-images.githubusercontent.com/41518918/142598757-a3557869-55e7-49e6-a5e7-36fe01a81043.png)

**Comment by multiplemonomials** [comment]
Interesting, looks like that error is coming from gcc itself when it tries to execute the assembler.  Does the path in the red box actually exist on the disk?

Also, what happens if you use mbedignore (try the one in mbed-cmake-example-project) to cut the set of included mbed modules down to a lower number?  That should reduce the amount of flags being passed on the command line by a ton,

**Comment by nasihs** [comment]
> Interesting, looks like that error is coming from gcc itself when it tries to execute the assembler. Does the path in the red box actually exist on the disk?
> 
> Also, what happens if you use mbedignore (try the one in mbed-cmake-example-project) to cut the set of included mbed modules down to a lower number? That should reduce the amount of flags being passed on the command line by a ton,

Thanks for your patience! The path in the red box exists. I try to use mbedignore, both mingw32 and ninja work well.
