### ISSUE TITLE
Wiki - macOS - Install GNU ARM toolchain

### ISSUE THREAD

**Issue by ladislas** [USCRPL/mbed-cmake#5]
On macOS, the [wiki](https://github.com/USCRPL/mbed-cmake/wiki/Toolchain-Setup#on-mac) describes several tests to install the GNU ARM Toolchain.

One simpler way using `brew` is use https://github.com/osx-cross/homebrew-arm

```console
$ brew tap osx-cross/arm
$ brew install arm-gcc-bin
```

It does the same in one/two steps and adds it to path automatically.

**Comment by multiplemonomials** [comment]
Added to the wiki! https://github.com/USCRPL/mbed-cmake/wiki/Toolchain-Setup

Thanks!
