### ISSUE TITLE
Use snake_case for all files

### ISSUE THREAD

**Issue by ladislas** [USCRPL/mbed-cmake#7]
In https://github.com/USCRPL/mbed-cmake/tree/master/cmake, file's names use different cases, which makes it harder to read and add complexity ("why is this file's name written this way and this one's not, what does that mean?").

I'd like to provide a PR that rewrites all the file's names as `snake_case` to follow what mbed is already doing. 

Are you okay with that?

**Comment by multiplemonomials** [comment]
I'm actually working on some changes (in `arm-compiler-support` branch), and one of the things is cleaning up the case of those files.  It was bothering me too :).  FWIW I think CamelCase is the CMake standard.
