### ISSUE TITLE
Scripts/memap

### ISSUE THREAD

**Issue by ladislas** [USCRPL/mbed-cmake#8]
mbed-cmake provides its own `memap.py` script. Is there a reason for not using the one provided by mbed in `mbed-os/tools/memap.py`?

**Comment by multiplemonomials** [comment]
I had to make substantial changes to it, mainly because CMake uses .obj for the object file extension on Windows, and this explodes several of the regexes in it.  I think there was also a forward slash vs backslash issue on Windows? I don't really remember, it was a year+ ago.

**Comment by multiplemonomials** [comment]
Oh, whaddaya know, turns out this exists: https://github.com/ARMmbed/mbed-os/pull/9851

**Comment by multiplemonomials** [comment]
Should be fixed in #9!
